FROM ghcr.io/mlflow/mlflow:latest

USER root

# Install dependencies required for psycopg2
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    python3-dev \
    && pip install --no-cache-dir psycopg2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
